# Generated by Django 2.2 on 2021-05-16 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to='trip_app.User'),
        ),
        migrations.AddField(
            model_name='trip',
            name='going',
            field=models.ManyToManyField(related_name='my_trips', to='trip_app.User'),
        ),
    ]
